### PR TITLE
Major Update to Main Activity

### PR DESCRIPTION
**Pull request by elitexen**
Let's try this again...

### CODE REVIEW

**Comment by blackboxembedded** [comment]
Is there anything I can do to help? I've paused any work so as not to cause you any more conflicts :)

**Comment by elitexen** [comment]
So I'm not sure what's going on with the repository and I'm not sure what to do to fix things on my end.  

I rebased when you originally recommended it, accepted all your changes.  And then went through and updated the code on again on my end and committed/pushed it.
image

Since you were still seeing conflicts, I tried rebasing again and it first warned me not to proceed since it would create duplicate commits but when I tried to proceed anyways and it would never complete.  It would just get stuck in an infinite loop as I was going through the conflicts.  It would say something like "must resolve all conflicts to merge but then it didn't show any conflicts and would just give me an abort/retry option".  So then I gave in and completely deleted my repository to start fresh and reforked from the original.  But once I started trying to work on it I noticed there was some old code for example the Data class was still being referenced when you had already renamed it in one of your commits.  Just to be extra safe, I deleted my fork again and tried a new fork with a new name "-AOSP" rather than "-ANDROID" to ensure there wasn't any weird cache issue on my end.  Still the same problem.  Finally I went back to your original repository and it looks like the commit wasn't fully applied or something.  Because you can still see the Data class here where it should be MotorcycleData.  Line #80 of MainActivity.java is one example but there are a bunch
image

This is a fresh download I pulled off the main repo minutes ago just to confirm.  
image

**Comment by blackboxembedded** [comment]
Let me double-check, maybe something didn't get committed on my end.

**Comment by blackboxembedded** [comment]
There was one file I forgot to commit. I'm so sorry for causing you extra trouble. 🤦

**Comment by elitexen** [comment]
No worries.  I'll fork it again and reapply the changes this afternoon.  I've got a list of other changes planned but I'm heading Colorado tonight to go ride around on my Honda for a month so I'll have to pause for a bit.  Maybe I'll see if I can get the iOS version updated in the interim 🤞🤞

**Comment by blackboxembedded** [comment]
Thanks again, these are great changes!

I'm out of Colorado Springs, maybe I can buy you a beer? :) 

My email is keith.conger@blackboxemebedded.com if you want to reach me directly.

**Comment by elitexen** [comment]
I'm taking the most circuitous but I'll definitely give you a heads up a couple days before I pass through Colorado Springs.  Probably sometime between the 5th and 9th.  Is there a cheap place to buy/mount tires there?  I think I got tires in Co Springs on my Ducati years ago but I can't remember where.  And I'm guessing by then I'll be getting close to needing another set.

**Comment by blackboxembedded** [comment]
Cool, let me know.

I can give you some suggestions but I'm not sure if they are cheap. I change my own tires, so I just order online.

**Comment by blackboxembedded** [comment]
I hope you made it home safe and had a great trip besides your tire-changing adventures. Sorry, we couldn't meet up. Let me know if you want to do a call.

**Pull request closed without merging**
