### PR TITLE
Minor Fix LeanAngleMax

### PR DESCRIPTION
**Pull request by elitexen**
Rename LeanAngle to LeanAngleBt to avoid ambiguity with LeanAngleBike. Fixed implementation of LeanAngleMax incorporated into SetLeanAngle function.

### CODE REVIEW

**Comment by blackboxembedded** [comment]
Thank you for the PR, would you mind rebasing?

**Comment by elitexen** [comment]
Not sure why github didn't notify me of your comment and of course I'm just seeing this when I came to create a much larger pull request😅🤦‍♂️.  I just rebased and accepted all your changes.  I will create a new pull request shortly with my changes.  I just have to redo a few because it looks like we had some conflicts.

**Comment by elitexen** [comment]
Ok I think I'm done rebasing.  Hopefully I did that correctly 🤞🤞

**Comment by elitexen** [comment]
Before MemCache and updateDisplay changes:
Before MemCache Optimization

After MemCache and updateDisplay changes.  Decreased CPU usage and overall memory usage (less garbage collection and flash IO).
After MemCache Optimization

Screenshot_20240814_195509

**Comment by blackboxembedded** [comment]
> Ok I think I'm done rebasing. Hopefully I did that correctly 🤞🤞

Thanks again for the amazing contributions. It looks like there are still some conflicts left.

**Pull request closed without merging**
